export const SET_PRODUCTS = "SET_PRODUCTS";
export const RESET_PRODUCTS = "RESET_PRODUCTS";
export const SET_SPECIFIC_PRODUCT = "SET_SPECIFIC_PRODUCT";
export const RESET_SPECIFIC_PRODUCT = "RESET_SPECIFIC_PRODUCT";

export const SET_CATEGORIES_WITH_SUB_CATEGORIES =
  "SET_CATEGORIES_WITH_SUB_CATEGORIES";
export const RESET_CATEGORIES_WITH_SUB_CATEGORIES =
  "RESET_CATEGORIES_WITH_SUB_CATEGORIES";
